### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by quithake** [bin-maker/EasyFish#8]
![image](https://github.com/bin-maker/EasyFish/assets/102508010/ad25eeb9-e0b1-43b5-8221-d2c764ae16df)
点击就弹个框，是缺了什么吗

**Comment by bin-maker** [comment]
去除无用字符串信息导致lib出错，自己电脑上编译用的是调试库，所以未产生该情况，干净虚拟机WIN7中编译后运行确实存在该问题，马上修复

**Comment by bin-maker** [comment]
> ![image](https://user-images.githubusercontent.com/102508010/243551080-ad25eeb9-e0b1-43b5-8221-d2c764ae16df.png) 点击就弹个框，是缺了什么吗

已修复，请重新下载运行
