### ISSUE TITLE
无法捕捉到数据

### ISSUE THREAD

**Issue by oldhand2016** [bin-maker/EasyFish#9]
大佬，按照的语雀上面的步骤一步一步走的，所有都配置好了，就是无法捕捉到数据.
 问题现象如下图：

![2024-02-15_00-48](https://github.com/bin-maker/EasyFish/assets/9305738/72e62389-48c6-46db-ace7-db1affb80360)

操作依据如下图：

![2024-02-15_00-46](https://github.com/bin-maker/EasyFish/assets/9305738/e0ea9f55-0b4e-4fb4-9235-ba3983aed822)
配置如下图：
![20240215004539](https://github.com/bin-maker/EasyFish/assets/9305738/115175b1-99fa-4228-bf85-48f59058c77f)
配置如下图：
![20240215004710](https://github.com/bin-maker/EasyFish/assets/9305738/62542a44-1950-4765-855f-a5584971c554)

**Comment by bin-maker** [comment]
加我微信，具体沟通下，vx：zaijian
